### PR TITLE
Week 2 Challenge - Ui5 Walkthrough on Kyma

### PR DESCRIPTION
**Pull request by jacobahtan**

### CODE REVIEW

**Comment by qmacro** [comment]
Hi there @jacobahtan  - if you're just submitting your challenge entry, you don't need to send a PR to this repo. Just check the instructions in the [Challenges](https://github.com/SAP-samples/sap-community-code-challenge-cloud-native/blob/main/Challenges.md) file. Thanks! 👍

**Comment by qmacro** [comment]
Whoops, my mistake, re-opening. Apologies!

**Comment by jacobahtan** [comment]
It says, "In this week's challenge you have to containerize your own service and deploy it to the SAP BTP, Kyma runtime. Use the forked repository to create your project and needed files, **open a Pull Request when you're done.**"

**Comment by KevinMuessig** [comment]
Hi @jacobahtan ,

thanks for opening the PR. There was a mistake from my side. We do not require a PR from you! The only thing I need as a submission from your side is a screenshot of your deployed service as well as the deployment.yaml in the [SAP Community Code Challenge - Let's set sail](https://groups.community.sap.com/t5/application-development/sap-community-code-challenge-let-s-set-sail-for-cloud-native/m-p/5748/thread-id/60) for Cloud Native Island! thread.

I am sorry if that caused any inconvenience for you and thank you for participating in the challenge :)

Cheers,
KM

**Comment by jacobahtan** [comment]
Thank you for clarify, Kevin~ Cheers!

**Pull request closed without merging**
